(kill-local-variable 'hl-paren-overlays)
(mapc 'delete-overlay hl-paren-overlays)
(hl-paren-create-overlays)
(defun test ()
  (interactive)
  (let ((overlays hl-paren-overlays)
        (pos (point))
        pos1 pos2)
    (save-excursion
      (condition-case err
          (while (and (setq pos1 (cadr (syntax-ppss pos1)))
                      (cdr overlays))
            (move-overlay (pop overlays) pos1 (1+ pos1))
            (when (setq pos2 (scan-sexps pos1 1))
              (move-overlay (pop overlays) (1- pos2) pos2)
              )
            )
        (error nil)
        )
      (goto-char pos)
      )
    (dolist (ov overlays)
      (move-overlay ov 1 1)
      )
    )
  )

(set-marker (mark-marker) (point))

(defface highlight
  ’((((class color) (min-colors 88) (background light))
     :background "darkseagreen2")
    (((class color) (min-colors 88) (background dark))
     :background "darkolivegreen")
    (((class color) (min-colors 16) (background light))
     :background "darkseagreen2")
    (((class color) (min-colors 16) (background dark))
     :background "darkolivegreen")
    (((class color) (min-colors 8))
     :background "green" :foreground "black")
    (t :inverse-video t))
   "Basic face for highlighting."
   :group ’basic-faces)

